apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spammer
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-custom-4-16384
        name: spammer
        databases:
          - name: spammer
            envVarPrefix: DATABASE
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
      rules:
        - application: spurtedu
  secureLogs:
    enabled: true
  envFrom:
    - secret: spammer
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spammer-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
